
import { Insight } from "./types";
import { OpenAI } from "openai";

const openai = process.env.OPENAI_API_KEY ? new OpenAI({ apiKey: process.env.OPENAI_API_KEY }) : null;

export async function explainInsight(insight: Insight): Promise<string> {
    // 1. Check for GPT Availability
    if (openai && process.env.COPILOT_GPT_ENABLED === 'true') {
        try {
            const completion = await openai.chat.completions.create({
                model: process.env.COPILOT_GPT_MODEL || "gpt-4o-mini",
                messages: [
                    { role: "system", content: "You are a financial analyst. Summarize the following insight data into one clear sentence. Do not invent numbers. Be professional." },
                    { role: "user", content: `Title: ${insight.title}\nSummary: ${insight.summary}\nData: ${JSON.stringify(insight.evidence_json)}` }
                ]
            });
            return completion.choices[0].message.content || insight.summary;
        } catch (error) {
            console.error("GPT Error:", error);
            // Fallback
        }
    }

    // 2. Deterministic Template Fallback
    // If GPT is off or fails, return a clean formatted string based on kind
    switch (insight.kind) {
        case 'project_health':
            const score = insight.evidence_json?.score;
            if (score < 50) return `Critically low score (${score}). Major risks in overdue payments and data freshness.`;
            if (score < 80) return `Moderate score (${score}). Some attention needed on aging debt.`;
            return `Excellent score (${score}). Operations are smooth.`;

        case 'collections':
            return `Detected ${insight.evidence_json?.count || 'multiple'} overdue items. Immediate collection recommended.`;

        default:
            return insight.summary; // Use the deterministic summary generated by rules.ts
    }
}
